/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TaskFilters: typeof import('./src/components/tasks/TaskFilters.vue')['default']
    TaskForm: typeof import('./src/components/tasks/TaskForm.vue')['default']
    TaskList: typeof import('./src/components/tasks/TaskList.vue')['default']
    TaskStatsCard: typeof import('./src/components/tasks/TaskStatsCard.vue')['default']
  }
}
